### PR TITLE
wrong entry was passed to the caching service from the data processing service

### PR DESCRIPTION
**Pull request by BondarencoM**
Cheers to @larsverp and his validation, that helped spot it much quicker.

The bug slipped into develop because we don't have any tests for data processing service yet.

### CODE REVIEW

**Review by oererenn — DISMISSED** [review]

**Review by larsverp — CHANGES_REQUESTED** [review]
Damm, we completely missed this. We should write some tests for the data processing. I'll look into that today 👍🏼 

We should however **ALMOST NEVER** change a test (this change is an exception, because this test would fail with the new code), but maybe write another test to show the bug is solved? @michaelbahchevanov

**Comment by larsverp** [comment]
So we should write a test that fails with the old code, bu succeeds with the new code. In case this bug ever returns.

**Comment by BondarencoM** [comment]
> @michaelbahchevanov

lol, wrong Michael ?

**Comment by BondarencoM** [comment]
@larsverp I guess this pull request doesn't get approved until I do that, so we'll not forget ^^

**Comment by larsverp** [comment]
> > @michaelbahchevanov
> 
> lol, wrong Michael ?

Oops....

**Comment by larsverp** [comment]
@BondarencoM I will approve :)

**Review by larsverp — DISMISSED** [review]

**Review by larsverp — APPROVED** [review]

**Review by oererenn — APPROVED** [review]

**Pull request merged**
